### ISSUE TITLE
add-on only works after disable/enable

### ISSUE THREAD

**Issue by boldcompany** [sblask/firefox-open-tabs-next-to-current#1]
Using Firefox 33.1.

After starting/restarting Firefox, this add-on does not work unless I first disable and then re-enable it. I am not sure if something loads after this add-on that overrides the functionality; maybe by disable/re-enable it then overrides the other something?

This add-on should enforce its functionality so it automatically starts working after launch of Firefox.

**Comment by sblask** [comment]
Closing this until there is more information.
