### ISSUE TITLE
Option to avoid switching to tab

### ISSUE THREAD

**Issue by brettz9** [sblask/firefox-open-tabs-next-to-current#10]
Hi,

I love the ability provided by your add-on, but it seems to inevitably switch to the newly opened tab. Can you add config to avoid doing this? This is useful, e.g., when opening many links on a page using an add-on which opens tabs at the end; without this option, I have to keep going back to the page with the links.

I would also suggest defaulting to (or exclusively using) the setting already in Firefox's options, "When I open a link in a new tab, switch to it immediately".

**Comment by sblask** [comment]
This add-on does only move opening tabs and does not change the way they are opened. You have to use the option you mentioned to change whether a new tab is opened in the background or not. I have the option ticked so when I click on a link while having `ctrl` pressed, the link opens in a new tab, when I have `ctrl-shift` pressed, it opens in a background tab. But this is basic Firefox functionality and has nothing to do with this add-on.

**Comment by brettz9** [comment]
Sorry, I had not checked carefully--it was my own add-on by using the Add-on SDK `tabs.open` without setting `inBackground` to the value of `browser.tabs.loadInBackground` (now fixed).
