### ISSUE TITLE
1Password

### ISSUE THREAD

**Issue by 3ckH4rd** [sblask/firefox-open-tabs-next-to-current#11]
If I use OpenTabsNextToCurrent with Stylish, 1Password doesnt open websites correctly when using "open and fill". I hope you can reproduce and maybe fix it? The tab always loads the start page but not the one I wanted to open in 1Password.

**Comment by sblask** [comment]
This add-on only moves tabs, nothing else, so I would be very surprised if your problem would be caused by it. But anyway, I have no idea what you mean by 1Password.

**Comment by sblask** [comment]
Please re-open if you have more information.
