### ISSUE TITLE
Slows down Fx startup

### ISSUE THREAD

**Issue by gwarser** [sblask/firefox-open-tabs-next-to-current#12]
Firefox 45dev 64b on Linux Mint.

With disabled extension Fx is usable after around 6 seconds. I see below 0.5 second delay between painting of new tab search bar and speedial thumbnails.
Enable extension and restart two times.
I see ~3 seconds delay between when search bar on new tab page is visible, and when speeddial thumbnails are loaded. Fx startup time increase to ~9 seconds.

This is somehow related to extension configuration, because I see this behavior in other extensions (Google™ Translator)

**Comment by sblask** [comment]
This add-on isn't doing much. If there is a slow down, it's probably Firefox internals for general add-on loading. I tested and could see a slow down. I assume you tested with only this add-on and no others installed? It would be much more interesting if you'd tested with 10 others installed and then give me figures for having this add-on enabled/disabled. To reproduce I'd also need the names of all these add-ons... But I doubt I can do much any way.

**Comment by gwarser** [comment]
I was testing all my addons one by one because of this slowness, but above numbers (6s -> 9s) are from my current setup:
```
Add-on Update Checker	2.15	true	{891f0410-aaa2-11e0-9f1c-0800200c9a66}
Classic Theme Restorer	1.4.6.1	true	ClassicThemeRestorer@ArisT2Noia4dev
Cookie Controller	4.5	true	{ac2cfa60-bc96-11e0-962b-0800200c9a66}
Distill Web Monitor (formerly AlertBox)	1.4.9	true	alertbox@ajitk.com
FEBE	8.8.1	true	{4BBDD651-70CF-4821-84F8-2B918CF89CA3}
Feed Sidebar	8.0.4.1-signed	true	feedbar@efinke.com
FindBar Tweak	2.1.5	true	fbt@quicksaver
FireGestures	1.10.3	true	firegestures@xuldev.org
Greasemonkey	3.7beta2	true	{e4a8a97b-f2ed-450b-b12d-ee082ba24781}
Hide Caption Titlebar Plus	3.0.5	true	hidecaptionplus-dp@dummy.addons.mozilla.org
OmniSidebar	1.6.9	true	osb@quicksaver
uBlock Origin	1.6.0	true	uBlock0@raymondhill.net
YouTube High Definition	43.3	true	{7b1bf0b6-a1b9-42b0-b75d-252036438bdc}
```
This 3 seconds delay looks "constant". For example (approximately):
Using clean profile:
* no extension 3s 
* with otntc 5s
* with ublock 4s
* with ublock + otntc 7s

Third extension with this behavior is "YouTube Plus"

**Comment by sblask** [comment]
What I meant to say was that I can't see a slow down. Enabled or disabled, Firefox takes 10 seconds to start(I've got quite a few more add-ons than you). Also, enabling and disabling the add-on is practically instantaneous. I assume there are several add-ons that use the same internals as this one, so they are loaded in any case for me, but not for you...
