### ISSUE TITLE
"Add-on ... appears to be corrupt"

### ISSUE THREAD

**Issue by mde** [sblask/firefox-open-tabs-next-to-current#13]
Cannot install from the download page, using FF 44.

![screen shot 2016-01-29 at 10 44 08 am](https://cloud.githubusercontent.com/assets/757/12684718/55496722-c675-11e5-9b29-a6a71d86d26e.png)

**Comment by sblask** [comment]
Hm, I just tried and it worked. But I think there was some problem with the website that got fixed. If you could try again and let me know how it goes, that would be great. If you still have the problem, I can contact the mailinglist, nothing much else I can do about it from my side.

**Comment by sblask** [comment]
Please re-open if you have more information.

**Comment by mde** [comment]
I think there might have been something corrupt in my FF profile. I flushed everything and started with a fresh profile, and things seem to work fine. Thanks for the response!
