### ISSUE TITLE
Newly opened tabs missing from "reopen tab" (ctrl-shift-T)

### ISSUE THREAD

**Issue by jimbo1qaz** [sblask/firefox-open-tabs-next-to-current#14]
Say I open a tab by middle-clicking a link, or alt-Entering a search. Then I close it.

The tab is missing from ctrl-shift-T. This addon breaks "reopen tab" functionality.

Firefox Dev 46.0a2

**Comment by sblask** [comment]
Works for me on Firefox 44.0.2 Maybe it's broken in the Firefox version you are using? This add-on is only moving the tab being opened, nothing else, so I'd be surprised if it affects closing a tab....

**Comment by sblask** [comment]
Please re-open if you've got more information.
