### ISSUE TITLE
Remove language parameter from links to mozilla.org

### ISSUE THREAD

**Issue by anewuser** [sblask/firefox-open-tabs-next-to-current#15]
Update the links on the project description page, so that the Mozilla website will open in the user's preferred language:

https://addons.mozilla.org/en-US/firefox/addon/open-tabs-next-to-current/ → https://addons.mozilla.org/firefox/addon/open-tabs-next-to-current/

https://developer.mozilla.org/en-US/Add-ons/SDK → https://developer.mozilla.org/Add-ons/SDK

**Comment by sblask** [comment]
Done.
