### ISSUE TITLE
Context awared tab placement.

### ISSUE THREAD

**Issue by amosbird** [sblask/firefox-open-tabs-next-to-current#17]
Suppose I have three tabs : `1`, `2` and `3`, and the current tab is `2`. If I open three new tabs, currently it will end up like this : `1`, `2` , `6`, `5`, `4`, `3`. Is there a way to get this tab order : `1`, `2`, `4`, `5`, `6`, `3` ?

**Comment by sblask** [comment]
Isn't that the default behaviour? If not, there is certainly another add-on that is doing that. I am not interested in implementing it.
