### ISSUE TITLE
Deactivate when following a link and `browser.tabs.insertRelatedAfterCurrent` is true

### ISSUE THREAD

**Issue by brunoais** [sblask/firefox-open-tabs-next-to-current#19]
Is it possible to have this addon not act when:
- A link is opened in a new tab?
- `browser.tabs.insertRelatedAfterCurrent` is set to true?

My objective is to have `ctrl + T` + links opened externally + menus opened to appear next to the current tab but links opened in a web page appear as they were when I have insertRelatedAfterCurrent turned on.

Related to #17

**Comment by sblask** [comment]
Unfortunately it's not possible. All I know is that a tab is being opened, the API does not expose why/by what action a tab was opened.

**Comment by brunoais** [comment]
How about trying this (and then improve the detection means):
When a page is opened, place an event on the <body> E.g.

When opening the tab, listen for a ready state:
https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/tabs#ready

When you get the ready state, get the tab (the parameter) and place a contentScript.
E.g. here in the `contentScriptOptions` row
https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/tabs#Parameters_3

On the contentScript just do:

	document.body.addEventListener('mouseup', function(e){
		self.port.emit("clicked", true);
	}, true);
	
On the main script then do:

	var clickingTimeout = null;
	var clickingReactivate  = function (){
		state.reenable();
	}
	var clickingDeactivation = function (){
		clearTimeout(clickingTimeout);
		clickingTimeout = setTimeout(clickingReactivate, 500);
	}
	//...
		pageWorker.port.on('clicked', clickingDeactivation);
	//...

Docs: https://developer.mozilla.org/en-US/Add-ons/SDK/Guides/Content_Scripts#Accessing_port_in_the_content_script


It's not perfect or anything like that but I think it can be done as a starting point given that you don't have API to know the cause for the tab to open.

**Comment by sblask** [comment]
Thanks for the suggestion, but that's way too hacky for my taste. However, I checked and it should be possible to do what you want to do with the webextension API. I just need to find the time to migrate...

**Comment by brunoais** [comment]
I was afraid of that.
I can give you some assistance if you want. I've been wrestling with it recently.

**Comment by sblask** [comment]
I think it's not much to be done, but getting all the tooling to work and working around the signing will need some work and I just have to find the time first...

**Comment by sblask** [comment]
Now I actually had some time to read up and it seems rather straight forward, however I don't think I can do this: https://github.com/sblask/firefox-open-tabs-next-to-current/blob/master/index.js#L23 with webextensions? @brunoais Not directly related to this add-on: there doesn't seem to be an equivalent to `jpm test` any idea how to do that?

**Comment by brunoais** [comment]
I don't know what that event is for :S... Even after trying reading the [manual](https://developer.mozilla.org/en/docs/Web/Events).
https://github.com/mozilla/web-ext ?

**Comment by sblask** [comment]
The reason I need to listen to that event is that if Firefox crashes or it's closed while tabs are open, the order of the tabs is reversed by default. I need to disable the reordering during session restore to avoid that...

**Comment by brunoais** [comment]
Ah! OK. It is the event specifying that SessionStore is working on the tabs. So that's how your addon doesn't mess up tabs like others do... I see...
Can you try making a hybrid addon, then? It is still not possible for stable firefox but recently they made an API for communication between WebExtensions and Legacy addon and SDK addons.
Actually, there's a quite lighten up discussion about how WebExtensions can actually help anything actually useful and how they are still quite limited.

**Comment by sblask** [comment]
I think I will contact dev-addons to see whether they've got some suggestions first. A hybrid is a possibility, but I was hoping it wouldn't be necessary as I think I'd be aiming for less than 100 lines of code in a pure webextension.

**Comment by brunoais** [comment]
Either that or IRC: [irc:irc.mozilla.org/webextensions](irc:irc.mozilla.org/webextensions)

**Comment by sblask** [comment]
I was playing around with https://github.com/mdn/webextensions-examples/tree/master/tabs-tabs-tabs to see what's possible with the tab API I thought I could get the information necessary for your requirements from `openerTabId` (https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/Tab) But it's `undefined` :-S As I can't check the preferences and thus `insertRelatedAfterCurrent` I would have to implement the same logic (#17), but I would also need `openerTabId`. The problems just never end...

**Comment by sblask** [comment]
Opened a bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1311504

**Comment by brunoais** [comment]
Thanks for the update!
@sblask https://bugzilla.mozilla.org/show_bug.cgi?id=1311504#c1 <- They always ask that.

**Comment by sblask** [comment]
See #22, I think the beta I uploaded should do what you want.

**Comment by brunoais** [comment]
Thank you! I've been using for a bit longer than a week now.
It is working very well! The tab scroll is jumping around when a tab is opened #24 but I think that is an OK price to pay for having this problem solved.
