### ISSUE TITLE
Allow both opening of tabs right of the current and at the end of the list

### ISSUE THREAD

**Issue by krichter722** [sblask/firefox-open-tabs-next-to-current#2]
It'd be great to be able to decide whether to open a tab right to the current or at the end of the list of tabs of the current window (default behaviour). This could be realized by making the "New Tab" menu item in the file menu a menu with two menu items doing the former and the latter. This transformation should be configurable.

In order to handle the opening of tabs with <kbd>Ctrl</kbd>+<kbd>t</kbd> it be great to be able to configure whether 

  * a tab should be opened always right to the current or at the end of the list, 
  * a dialog should be displayed asking for what to do

An option to configure the keyboard shortcut to open a tab at the two locations could be added to a settings dialog (override the meaning of <kbd>Ctrl</kbd>+<kbd>t</kbd> and define a second shortcut for the counterpart action).

**Comment by sblask** [comment]
That's not that simple and I am not actually interested in adding menus. I could settle for exposing a method to quickly enable/disable opening next to current whose shortcut you can configure with https://addons.mozilla.org/en-US/firefox/addon/customizable-shortcuts/

**Comment by stanio** [comment]
I think making open new tab next to the current an alternative shortcut (f.e. <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>T</kbd>) which could be customized using the [other extension](https://addons.mozilla.org/addon/customizable-shortcuts) mentioned would be great.

**Comment by sblask** [comment]
I am currently working on adding a few options including this. Will be released soonish. https://github.com/sblask/firefox-open-tabs-next-to-current/pull/4

**Comment by sblask** [comment]
New version has been released.
