### ISSUE TITLE
Plans to migrate to WebExtensions

### ISSUE THREAD

**Issue by bastones** [sblask/firefox-open-tabs-next-to-current#23]
Hello,

Sorry if this has already been previously answered.

All of the add-ons (including this one) I use are legacy extensions - some of which won't be updated past version 57. I'm sure I won't be the last one to say I am very unhappy Mozilla are deciding to purge an entire add-on ecosystem at the expense of end users and developers :-(.

Given that Firefox is scheduled to drop support for legacy add-ons in version 57, due out in November, are there plans to migrate this add-on over to the WebExtensions platform before then?

Thanks.

**Comment by sblask** [comment]
See #22
