### ISSUE TITLE
Tab opens at end if a pinned tab is focused

### ISSUE THREAD

**Issue by benjaminjkraft** [sblask/firefox-open-tabs-next-to-current#25]
Previously, if I had a pinned tab selected, and opened a new tab (e.g. via Ctrl-T), it would open as the first (leftmost) non-pinned tab -- that is, as close to next to the current tab as possible.  Now, with v2.0.0, it opens as the last (rightmost) tab; this seems to be a regression.

**Comment by sblask** [comment]
That only worked by accident before, but I agree, it should be like it was before. I uploaded a new beta. Please check it out and let me know how it goes and if there are other problems!

**Comment by benjaminjkraft** [comment]
Works great, thanks very much for the quick response!

**Comment by NabiKAZ** [comment]
I use it: https://addons.mozilla.org/en-US/firefox/addon/tab-deque/
It's better and not have this problem.

**Comment by sblask** [comment]
The new version went through review today, so this is fixed for everybody now.

@NabiKAZ Tab Deque is for something rather different, but I am glad you like it, I wrote it ;-)

**Comment by NabiKAZ** [comment]
@sblask What's deference?

**Comment by sblask** [comment]
Open Tab Next To Current changes where a tab appears visually. Tab Deque does not visually change anything, it changes the logical order of tabs, i.e. which tab is selected when closing a tab and allows for "minimizing".

**Comment by NabiKAZ** [comment]
I think I was wrong. the version 1.1.5 of same add-on works well.
