### ISSUE TITLE
Link drag from one window to another moves to wrong position

### ISSUE THREAD

**Issue by Aq32** [sblask/firefox-open-tabs-next-to-current#27]
When dragging a link from one window to another to sandwich between tabs, the link will instead be opened in the first position. The link could also open in other positions dependent on which position the first window's tab (ie the tab position of the source link) starts on.

Confirmed on Firefox 54.0b8 32bit (Win10 x64) with Open Tabs Next to Current 2.0.2
Confirmed on Firefox 53.0.2 64bit (Linux Manjaro) with Open Tabs Next to Current 2.0.2

**Comment by sblask** [comment]
I can reproduce it and I think it would be funny if I could because I don't handle attach and detach. When I drag a tab to another window into the tab bar, it ends up right where it was indicated. When I don't drag it into the tab bar, a new window is created. Maybe you've got another add-on that causes this?

**Comment by Aq32** [comment]
I tested on a new profile and there are no other addons installed on both OS tests. 

The problem is not with dragging tabs to tabs. It's dragging a url/link from a webpage to the tab bar on a second window.

**Comment by sblask** [comment]
Got it! I uploaded a new beta: https://addons.mozilla.org/en-US/firefox/addon/open-tabs-next-to-current/versions/beta could you please check it out and let me know how it goes? I didn't have problems any more, but I don't usually use more than one window.

**Comment by sblask** [comment]
Btw, this also fixes the `+` button position in new windows. You didn't mention it, but it was the same problem.

**Comment by Aq32** [comment]
Yes. I thought it would be a simple fix but I'm surprised by how fast you responded. I can confirm on both OSes and versions of Firefox that it's fixed now. Thanks!
