### ISSUE TITLE
Tabs are Reordered on Multi-Window Session Restore

### ISSUE THREAD

**Issue by Kaisonic** [sblask/firefox-open-tabs-next-to-current#28]
Ever since the update that causes the known issue (tabs being moved after being opened), tabs are being reordered when Firefox is opened and a multi-window session is restored. It seems like the add-on is being triggered for every tab opened by the session restore, which is causing tabs to be re-ordered unpredictably. Is there a way to limit this add-on to only activate when a new tab is created from the "New Tab" button, rather than when Firefox is first opened and a session is being restored? I have two windows with several tabs each, and it seems like one window has its tabs basically reversed, and the other window has the last tab moved almost all the way to the left, but this behavior is not consistent.

Steps to Reproduce:
1. Open two Firefox windows with 5+ tabs each.
2. Close Firefox (File -> Exit, with session restore enabled).
3. Re-open Firefox.
4. Notice tabs are moved to new positions after Firefox is opened.

**Comment by sblask** [comment]
I had a really good way to handle this problem before, but with the new APIs, there isn't. I thought I had it covered by a heuristic, but apparently not :-( How do you do a multi window restore? Isn't only the last one recovered? Or do you use an add-on for that? That might cause the problem too...

**Comment by Kaisonic** [comment]
Nope, no add-ons - when I have "Show your windows and tabs from last time" selected for "When Firefox starts" in the General options page, if I close Firefox by choosing File -> Exit (aka menu button -> power button), then all my windows and tabs are closed at once, and then restored when I re-open Firefox.

**Comment by sblask** [comment]
I have difficulties debugging this and confirming any changes any make. I uploaded a new beta to https://addons.mozilla.org/firefox/addon/open-tabs-next-to-current/ (click link at the bottom) that might fix it. Would you mind installing it and letting me know how it goes? Thanks!

**Comment by Kaisonic** [comment]
Just installed 2.0.4 and it looks like you fixed it - my tabs stay where they were when I open Firefox. Thank you!

**Comment by Kaisonic** [comment]
Correction: I hadn't realized you didn't merge your fix attempt to 2.0.4, so after a couple more Firefox restarts, the behavior returned. I installed the Development channel version 2.0.3b3 and it looks like the fix worked. Thanks again!

**Comment by sblask** [comment]
The proper release version went through review today if you want to switch...
