### ISSUE TITLE
Works only for first tab on opening multiple tabs via bookmarks

### ISSUE THREAD

**Issue by Kilbourne** [sblask/firefox-open-tabs-next-to-current#29]

**Comment by sblask** [comment]
Seems like there is nothing I can do about it. I don't get the events I'd need to make this work :-(

**Comment by Kilbourne** [comment]
OK. There is something that FF changes because some version ago it works. :( I often open multiple bks.

**Comment by sblask** [comment]
Yes, I rewrote this add-on as webextension, which is the only API that will be supported from Firefox 57. A lot of things have changed, events being one of them. What I would need to make this work is one created and one activated event per bookmark, but I only get one activated events no matter how many bookmarks I open. The order will probably be wrong too. I opened a bug for event order a while ago and nothing much has changed since...

**Comment by Kilbourne** [comment]
And which is the last legacy release? thanks

**Comment by sblask** [comment]
Last version that is not a webextension should be 1.1.5 https://addons.mozilla.org/en-US/firefox/addon/open-tabs-next-to-current/versions/

**Comment by grahamperrin** [comment]
@sblask @autonome I can, for example, get multiple tabs to the right – and adjacent to each other – with the **[l+c]** (link + comments) feature of Reddit Enhancement Suite (RES) [5.12.8 with Waterfox Classic](https://www.reddit.com/comments/9s9e4l/-/ege3q48/). 

In this screen recording, with Vertical Tabs Reloaded the two tabs appear immediately _below_ what was the current tab:

[multiple new tabs below i.e. to the right, and adjacent to each other.zip](https://github.com/sblask/webextension-open-tabs-next-to-current/files/3720200/multiple.new.tabs.below.i.e.to.the.right.and.adjacent.to.each.other.zip)

Two frames from the recording: 

![2019-10-12 04:43:23 frame a](https://user-images.githubusercontent.com/192271/66694624-5de07800-ecad-11e9-8601-49ee13d2870a.png)

![2019-10-12 04:43:23 frame b](https://user-images.githubusercontent.com/192271/66694622-5c16b480-ecad-11e9-855f-7ba6eafbe94f.png)

Does this help? Or do you remain constrained by WebExtensions APIs when opening multiple tabs from the Library window?

**Comment by grahamperrin** [comment]
Sorry, ignore my previous comment. 

I was confused by this known issue at <https://addons.mozilla.org/addon/open-tabs-next-to-current/>: 

> - when opening multiple tabs at once, only one of them is opened at the right

Is that no longer an issue? 

> opening multiple tabs from the Library window?

AFAICT this is bugged with Waterfox Classic but not with Firefox 69.0.2.

**Comment by mttkay** [comment]
Not sure if related: when I restore an entire window incl. tabs from "History -> Recently closed windows", some of the tabs will be re-sorted all the way to the left, which is really confusing.

Same issue, or should I open a new bug report?

**Comment by mttkay** [comment]
I also want to say that this has only started to happen recently, so maybe it's a regression with a new FF version (100 or newer?)

**Comment by sblask** [comment]
I don't think anything has changed in the API. So I don't get the events I need to make it work properly with several tabs at once. If it does or doesn't work is because of some internal behaviour beyond my control.
