### ISSUE TITLE
Tab position, usability improvment.

### ISSUE THREAD

**Issue by Nidre** [sblask/firefox-open-tabs-next-to-current#3]
It is more of a feature request rather than an issue.

Case a:
If user uses keyboard shortcut (ctrl + t), the new tab opens next to currently selected tab. As it is now.
Case b:
If user click to open new tab button on Firefox(Right end of the tab bar). The tab opens at the end of the list.

I believe it is more appropriate in terms if UX, since new tab button is more related to the right end rather than, right of the selected tab. As a user, I simply am focused on the new tab button, therefore I believe it is more likely that I would expect the tab to appear at the end of tab list. At least that is the case for me and some people that I know.

I have previously implemented this feature by Forking this repository, but it broke with E10's and I do not have any time to maintain that repository. Below is the link to the repository if you think that feature is worth implementing.

https://github.com/Nidre/firefox-open-tabs-next-to-current

Thank You

**Comment by Nidre** [comment]
I have fixed the bug and it currently works with my version of this add-on.

**Comment by sblask** [comment]
I am working on this and only the hotkey functionality is missing(which should be simple though as I moved everything over to the SDK): https://github.com/sblask/firefox-open-tabs-next-to-current/pull/4

**Comment by Nidre** [comment]
@sblask I have already done those change son my Branch. Hotkey + the mentioned feature. You can take a look if it helps in anyway.
