### ISSUE TITLE
New keyboard shortcut for default behaviour

### ISSUE THREAD

**Issue by valenting** [sblask/firefox-open-tabs-next-to-current#5]
Ctrl-Alt-T is a system shortcut in Gnome-Ubuntu (and other Gnome distributions) which opens the terminal.
It would be great if the shortcut was configurable.

**Comment by sblask** [comment]
Yeah, Ubuntu is a little greedy there, having 2 shortcuts for the same thing (I always use windows-T). I disabled Ctrl-Alt-T for that...

I am currently working on another add-on, but when I've got the time, I will look into adding a shortcut. There is no good API for that currently :-(

**Comment by sblask** [comment]
See #22
