### ISSUE TITLE
Conflict with "Session Manager" add-on: Tab order reversed on session restore

### ISSUE THREAD

**Issue by mesvam** [sblask/firefox-open-tabs-next-to-current#7]
I'm having the same issue as mentioned [here](https://addons.mozilla.org/en-us/firefox/addon/open-tabs-next-to-current/reviews/737618/). This seems to be a conflict with [Session Manager](https://addons.mozilla.org/en-US/firefox/addon/session-manager/).

When restoring tabs with Session Manager, the tab order of the last `n-1` tabs are reversed. For example, when restoring tabs `(a, b, c, d, e)`, the order when restored is `(a, e, d, c, b)`. From the behavior, it seems like this add-on hooks into something used by Session Manager, so I'm not sure how fixable this is on your end.

**Comment by sblask** [comment]
I am aware of this problem, but did not have the time to look into it yet. The add-on doesn't do anything with the session manager, it acts when tabs are opened, which seems to include tabs being restored and they seem to be restored from right to left, which makes the add-on flip the order. However, I never have this problem(I restore my session using the Firefox built-in functionality on every start, i.e. not using the button on the homepage). As you are using an add-on, it might not be fixable...

**Comment by sblask** [comment]
I just uploaded a new version(1.1.4) that fixes the problem for the Firefox session manager, I hope it also does for you. You can download it here: https://addons.mozilla.org/en-US/firefox/addon/open-tabs-next-to-current/versions/ or wait for the review after which it should be updated automatically.

**Comment by mesvam** [comment]
It works beautifully with the Session Manager add-on now. I've never noticed problems with the built in Firefox session manager, and don't think that was the issue.

Thanks

**Comment by Gitoffthelawn** [comment]
Does this issue affect the "Plus" version?

**Comment by sblask** [comment]
@Gitoffthelawn Not the right place to ask this? I have nothing to do with it...

**Comment by Gitoffthelawn** [comment]
My error and apologies... I forgot the Plus version is a fork from a different developer.

**Comment by mesvam** [comment]
Sorry to bother, but with the new 0.8.1.13 update of Session Manger, this problematic behavior is back again. Reverting back to 1.1.3 of this add-on before the patch doesn't seem to change anything.

**Comment by sblask** [comment]
@mesvam Not sure I can do anything about it. My patch added listening to an event to see whether a session is being restored (https://github.com/sblask/firefox-open-tabs-next-to-current/blob/master/index.js#L23) and deactivated moving any tabs during that time. So it seems this event is no longer fired. Might be the Session Manager that doesn't do it anymore, or a new Firefox version. The only thing I can think of is asking the developer of Session Manager to add an option to restore tabs in the reverse order.
