### ISSUE TITLE
Switching to previous tab after closing current

### ISSUE THREAD

**Issue by vkapas** [sblask/firefox-open-tabs-next-to-current#8]
By default, if I closing current tab Firefox will switch me on next tab. With «Open Tabs Next to Current» if I closing current tab Firefox switching me on **previous** tab.

Is it possible to use addon and return switching on next tab after closing current?

*Sorry for my English :-)*

**Comment by sblask** [comment]
This add-on only changes the display order of the tabs, not the way tabs are focused. There are other add-ons that do that. I wrote this one: https://addons.mozilla.org/en-US/firefox/addon/tab-deque/ but it might also not do what you want, you'll have to try to find out...

**Comment by vkapas** [comment]
**sblask**, please watch this short video, there I demonstrate my issue: https://youtu.be/pG_TZn_OfoY

There is different which tab is focusing after closing current tab with and without OpenTabsNextToCurrent addon.

**Comment by sblask** [comment]
I see what you mean, but my add-on doesn't change it, it's Firefox doing something funny. This kind of behaviour is exactly why I wrote https://addons.mozilla.org/en-US/firefox/addon/tab-deque/ so I'd get a predictable ordering. It might not be the ordering you want, but give it a go...
