### ISSUE TITLE
Romanian keyboard: AltGr+T opens a new tab instead of inserting diacritic ț

### ISSUE THREAD

**Issue by silviubogan** [sblask/firefox-open-tabs-next-to-current#9]
Please see [this Firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1231313). Thank you!

**Comment by sblask** [comment]
I was unaware of this issue: https://blogs.msdn.microsoft.com/oldnewthing/20040329-00/?p=40003 :-(

I have making the shortcut configurable on my todo list. Once done, this should not be an issue anymore. I will remove the ctrl-alt default...

**Comment by silviubogan** [comment]
Any news regarding this issue? 😃 Thank you!

**Comment by sblask** [comment]
I won't put any effort into the current form of the add-on and a migration to webextension is not currently possible because of missing APIs.

**Comment by sblask** [comment]
See #22
